name: Service

on:
  push:
    branches: [ master ]

  schedule:
    - cron: "0 0 * * *"

jobs:

  update-badges:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
    - name: Run Makefile to generate badges based on repositories languages and book listing.
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: make languages books

    - name: Set up Go latest stable version
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Update book covers
      run: make covers clean

    - name: Update repository.
      run: |
        BRANCH="$(git branch --show-current)"
        echo "Updating '${BRANCH}…'"
        git config --global user.email "jmurowaniecki@gmail.com"
        git config --global user.name  "John's Shadow 🜏"
        git commit -am '[skip ci] updating README…' && \
        git push origin ${BRANCH} || true
